# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Use new Python version
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Install via pip before running
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
