[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "conflowgen"
dynamic = [
    "version",
    "license",
    "description",
    "readme",
    "requires-python"
]
authors = [
  {name = "Marvin Kastner", email = "marvin.kastner@tuhh.de"},
]
