extend = "pyproject.toml"
src = ["conflowgen"]

[lint]

ignore = [
    "F821",  # Variables such as 'In' or 'display' are not detected and variables of imported Jupyter Notebook cannot be detected
    "E501",  # Allow long lines
    "E402",  # Module level imports are decided on by developers
    "E231",  # Ignore missing white space after ':' because it also affects f-string expressions which in fact haven't changed, see https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals

    "F401",  # No tedious re-export, also wrong flags on typing that is used in the doc strings
]
