from __future__ import annotations

import logging
import typing

import matplotlib.figure
import matplotlib.pyplot as plt
import pandas as pd

from conflowgen.analyses.container_flow_by_vehicle_instance_analysis import ContainerFlowByVehicleInstanceAnalysis
from conflowgen.descriptive_datatypes import VehicleIdentifier, FlowDirection
from conflowgen.domain_models.data_types.mode_of_transport import ModeOfTransport
from conflowgen.reporting import AbstractReportWithMatplotlib
from conflowgen.reporting.no_data_plot import no_data_graph


class ContainerFlowByVehicleInstanceAnalysisReport(AbstractReportWithMatplotlib):
    """
    This analysis report takes the data structure as generated by :class:`.ContainerFlowByVehicleInstanceAnalysis`
    and creates a comprehensible representation for the user, either as text or as a graph.
    The visual and table are expected to approximately look like in the
    `example ContainerFlowByVehicleInstanceAnalysisReport \
    <notebooks/analyses.ipynb#Container-Flow-By-Vehicle-Instance-Analysis-Report>`_.
    """

    report_description = """
    Analyze how many import, export, and transshipment containers were unloaded and loaded on each vehicle.
    """

    logger = logging.getLogger("conflowgen")

    def __init__(self):
        super().__init__()
        self._df = None
        self.analysis = ContainerFlowByVehicleInstanceAnalysis()

    def get_report_as_text(
            self, **kwargs
    ) -> str:
        """
        Keyword Args:
            start_date (datetime.datetime): The earliest arriving container that is included.
                Consider all containers if :obj:`None`.
            end_date (datetime.datetime): The latest departing container that is included.
                Consider all containers if :obj:`None`.

        Returns:
            The report in human-readable text format
        """
        container_flow = self._get_analysis(kwargs)

        report = "(pending)"

        # create string representation
        return report

    def _get_analysis(self, kwargs: dict) -> typing.Dict[
        ModeOfTransport, typing.Dict[VehicleIdentifier, typing.Dict[FlowDirection, (int, int)]]
    ]:
        start_date = kwargs.pop("start_date", None)
        end_date = kwargs.pop("end_date", None)
        assert len(kwargs) == 0, f"Keyword(s) {kwargs.keys()} have not been processed"

        container_flow = self.analysis.get_container_flow_by_vehicle(
            start_date=start_date,
            end_date=end_date
        )
        return container_flow

    def get_report_as_graph(self, **kwargs) -> matplotlib.figure.Figure:
        """
        Visualize the container flows (import, export, transshipment) over time.

        Returns:
             The diagram.
        """
        container_flow = self._get_analysis(kwargs)

        plain_table = []

        for mode_of_transport in (set(container_flow.keys()) - set([ModeOfTransport.truck])):
            for vehicle_identifier in container_flow[mode_of_transport].keys():
                for flow_direction in container_flow[mode_of_transport][vehicle_identifier]:
                    for journey_direction in container_flow[mode_of_transport][vehicle_identifier][flow_direction]:
                        handled_volume = container_flow[
                            mode_of_transport][vehicle_identifier][flow_direction][journey_direction]

                        plain_table.append(
                            (mode_of_transport, vehicle_identifier.id, vehicle_identifier.vehicle_name,
                             vehicle_identifier.service_name, vehicle_identifier.vehicle_arrival_time,
                             str(flow_direction), journey_direction, handled_volume)
                        )

        plot_title = "Container Flow By Vehicle Instance Analysis Report"

        if len(plain_table) == 0:
            fig, ax = no_data_graph()
            ax.set_title(plot_title)
            return fig

        column_names = ("mode_of_transport", "vehicle_id", "vehicle_name", "service_name", "vehicle_arrival_time",
                        "flow_direction", "journey_direction", "handled_volume")

        df = pd.DataFrame(plain_table)
        df.columns = column_names
        df.set_index("vehicle_arrival_time", inplace=True)

        self._df = df

        fig, axes = plt.subplots(nrows=2 * (len(ModeOfTransport) - 1), figsize=(7, 20))
        i = 0
        for mode_of_transport in (set(ModeOfTransport) - set([ModeOfTransport.truck])):
            for journey_direction in ["inbound", "outbound"]:
                ax = axes[i]
                i += 1
                ax.set_title(f"{mode_of_transport} - {journey_direction}")
                df[(df["mode_of_transport"] == mode_of_transport)
                   & (df["journey_direction"] == journey_direction)
                   ].groupby("flow_direction")["handled_volume"].plot(ax=ax, linestyle=":", marker=".")

        plt.legend(loc='center left', bbox_to_anchor=(1, 0.5))

        plt.tight_layout()

        return fig
