name: Windows conda installation (conda not in PATH)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    name: Windows conda installation
    runs-on: windows-2019

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v3.4.1

    - uses: actions/checkout@v2

    - name: Install miniconda
      run: |
        Invoke-WebRequest -OutFile miniconda.exe -Uri `
        https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
        .\miniconda.exe /InstallationType=JustMe /RegisterPython=0

    - name: Create and update environment (miniconda is not in PATH)
      working-directory: .\examples\Jupyter_Notebook\
      run: |
        .\create-env.bat
        .\update-env.bat
