name: Install from repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize]
  schedule:
    - cron: '42 23 * * 3'  # every Wednesday at 23:42

jobs:
  build-conda:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: ConFlowGen installation via conda
    runs-on: ${{ matrix.os }}

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v3.4.1

    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""

    - name: Install ConFlowGen and run tests
      run: |
        conda activate base
        conda install -c conda-forge conflowgen pytest

    - name: Run tests
      run: |
        conda activate base
        python -m pytest --pyargs conflowgen


  build-pip:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: ConFlowGen installation via pip
    runs-on: ${{ matrix.os }}

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v3.4.1

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install ConFlowGen
      run: |
        python -m pip install conflowgen pytest

    - name: Run tests
      run: |
        python -m pytest --pyargs conflowgen
