name: Install from repository

on:
  schedule:
    - cron: '42 23 * * 3'  # every Wednesday at 23:42

jobs:
  build-conda-on-windows:

    name: ConFlowGen installation via conda on Windows
    runs-on: windows-latest

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v3.4.1

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""

    - name: Install ConFlowGen
      run: |
        conda install -c conda-forge conflowgen pytest

    - name: Run tests
      run: |
        python -m pytest --pyargs conflowgen

  build-conda-on-linux:

    name: ConFlowGen installation via conda on Linux
    runs-on: ubuntu-latest

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v3.4.1

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""

    - name: Install ConFlowGen
      run: |
        conda init bash
        eval "$(conda shell.bash hook)"
        conda activate base
        conda install -c conda-forge conflowgen pytest

    - name: Run tests
      run: |
        eval "$(conda shell.bash hook)"
        conda activate base
        python -m pytest --pyargs conflowgen

  build-pip:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: ConFlowGen installation via pip
    runs-on: ${{ matrix.os }}

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v3.4.1

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install ConFlowGen
      run: |
        python -m pip install conflowgen pytest

    - name: Run tests
      run: |
        python -m pytest --pyargs conflowgen
