name: Install from repository

on:
  schedule:
    - cron: '42 23 * * 3'  # every Wednesday at 23:42
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build-conda-on-windows:

    name: ConFlowGen installation via conda on Windows
    runs-on: windows-latest
    env:
      MPLBACKEND: Agg

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v5

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: true
        python-version: '3.10'

    - name: Install ConFlowGen
      run: |
        conda clean -ity
        conda info
        conda search conflowgen -c conda-forge --info
        conda create -n test-install-conflowgen -c conda-forge conflowgen pytest

    - name: Prepare tests
      run: |
        conda activate test-install-conflowgen
        conda update conflowgen
        conda install pillow>=9.0

    - name: Run tests
      run: |
        conda activate test-install-conflowgen
        python -c "import conflowgen; print(conflowgen.__version__)"
        python -m pytest --pyargs conflowgen

  build-conda-on-linux:

    name: ConFlowGen installation via conda on Linux
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v5

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""

    - name: Install ConFlowGen
      run: |
        conda init bash
        eval "$(conda shell.bash hook)"
        conda clean -ity
        conda info
        conda search conflowgen -c conda-forge --info
        conda activate base
        conda create -n test-install-conflowgen -c conda-forge conflowgen pytest

    - name: Run tests
      run: |
        eval "$(conda shell.bash hook)"
        conda activate test-install-conflowgen
        python -c "import conflowgen; print(conflowgen.__version__)"
        python -m pytest --pyargs conflowgen

  build-pip:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    name: ConFlowGen installation via pip
    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg

    steps:

    - name: Skip Duplicate Actions
      uses: fkirc/skip-duplicate-actions@v5

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Use latest version of pip
      run: |
        python -m pip install --upgrade pip

    - name: Install ConFlowGen
      run: |
        python -m pip install conflowgen pytest
        python -m pip show --verbose conflowgen

    - name: Run tests
      run: |
        python -c "import conflowgen; print(conflowgen.__version__)"
        python -m pytest --pyargs conflowgen
